// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6TvXVd_awTA7PCKEGVkp6e0Y_elIf4bo',
    appId: '1:843139115547:web:b39842a14d9d938c42a6be',
    messagingSenderId: '843139115547',
    projectId: 'todo-project-e02b5',
    authDomain: 'todo-project-e02b5.firebaseapp.com',
    storageBucket: 'todo-project-e02b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxh08ACN8MkDzq84m6V9n2WUv7ruNA7FM',
    appId: '1:843139115547:android:9de0d68e07f423e042a6be',
    messagingSenderId: '843139115547',
    projectId: 'todo-project-e02b5',
    storageBucket: 'todo-project-e02b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hB1eqLpuXaM1uFg-FrAypxla7nX2lBc',
    appId: '1:843139115547:ios:e282db6dbc8d128442a6be',
    messagingSenderId: '843139115547',
    projectId: 'todo-project-e02b5',
    storageBucket: 'todo-project-e02b5.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
